Problems may be designed for the following topics so that students can get hands on
experience in using python for natural language processing:
• Part of Speech tagging
• N-gram

In [ ]:
from nltk.sem.boxer import NltkDrtBoxerDrsInterpreter
import nltk
from nltk import word_tokenize
nltk.download('punkt')#punkt is used for tokenising sentence and averaged perceptron
nltk.download('averaged_perceptron_tagger')
nltk.download('tagsets')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package tagsets to /root/nltk_data...
[nltk_data]   Package tagsets is already up-to-date!

True

In [ ]:
nltk.help.upenn_tagset()

$: dollar
    $ -$ --$ A$ C$ HK$ M$ NZ$ S$ U.S.$ US$
'': closing quotation mark
    ' ''
(: opening parenthesis
    ( [ {
): closing parenthesis
    ) ] }
,: comma
    ,
--: dash
    --
.: sentence terminator
    . ! ?
:: colon or ellipsis
    : ; ...
CC: conjunction, coordinating
    & 'n and both but either et for less minus neither nor or plus so
    therefore times v. versus vs. whether yet
CD: numeral, cardinal
    mid-1890 nine-thirty forty-two one-tenth ten million 0.5 one forty-
    seven 1987 twenty '79 zero two 78-degrees eighty-four IX '60s .025
    fifteen 271,124 dozen quintillion DM2,000 ...
DT: determiner
    all an another any both del each either every half la many much nary
    neither no some such that the them these this those
EX: existential there
    there
FW: foreign word
    gemeinschaft hund ich jeux habeas Haementeria Herr K'ang-si vous
    lutihaw alai je jour objets salutaris fille quibusdam pas trop Monte
    terram fiche oui corporis ...
IN: preposition or conjunction, subordinating
    astride among uppon whether out inside pro despite on by throughout
    below within for towards near behind atop around if like until below
    next into if beside ...
JJ: adjective or numeral, ordinal
    third ill-mannered pre-war regrettable oiled calamitous first separable
    ectoplasmic battery-powered participatory fourth still-to-be-named
    multilingual multi-disciplinary ...
JJR: adjective, comparative
    bleaker braver breezier briefer brighter brisker broader bumper busier
    calmer cheaper choosier cleaner clearer closer colder commoner costlier
    cozier creamier crunchier cuter ...
JJS: adjective, superlative
    calmest cheapest choicest classiest cleanest clearest closest commonest
    corniest costliest crassest creepiest crudest cutest darkest deadliest
    dearest deepest densest dinkiest ...
LS: list item marker
    A A. B B. C C. D E F First G H I J K One SP-44001 SP-44002 SP-44005
    SP-44007 Second Third Three Two * a b c d first five four one six three
    two
MD: modal auxiliary
    can cannot could couldn't dare may might must need ought shall should
    shouldn't will would
NN: noun, common, singular or mass
    common-carrier cabbage knuckle-duster Casino afghan shed thermostat
    investment slide humour falloff slick wind hyena override subhumanity
    machinist ...
NNP: noun, proper, singular
    Motown Venneboerger Czestochwa Ranzer Conchita Trumplane Christos
    Oceanside Escobar Kreisler Sawyer Cougar Yvette Ervin ODI Darryl CTCA
    Shannon A.K.C. Meltex Liverpool ...
NNPS: noun, proper, plural
    Americans Americas Amharas Amityvilles Amusements Anarcho-Syndicalists
    Andalusians Andes Andruses Angels Animals Anthony Antilles Antiques
    Apache Apaches Apocrypha ...
NNS: noun, common, plural
    undergraduates scotches bric-a-brac products bodyguards facets coasts
    divestitures storehouses designs clubs fragrances averages
    subjectivists apprehensions muses factory-jobs ...
PDT: pre-determiner
    all both half many quite such sure this
POS: genitive marker
    ' 's
PRP: pronoun, personal
    hers herself him himself hisself it itself me myself one oneself ours
    ourselves ownself self she thee theirs them themselves they thou thy us
PRP$: pronoun, possessive
    her his mine my our ours their thy your
RB: adverb
    occasionally unabatingly maddeningly adventurously professedly
    stirringly prominently technologically magisterially predominately
    swiftly fiscally pitilessly ...
RBR: adverb, comparative
    further gloomier grander graver greater grimmer harder harsher
    healthier heavier higher however larger later leaner lengthier less-
    perfectly lesser lonelier longer louder lower more ...
RBS: adverb, superlative
    best biggest bluntest earliest farthest first furthest hardest
    heartiest highest largest least less most nearest second tightest worst
RP: particle
    aboard about across along apart around aside at away back before behind
    by crop down ever fast for forth from go high i.e. in into just later
    low more off on open out over per pie raising start teeth that through
    under unto up up-pp upon whole with you
SYM: symbol
    % & ' '' ''. ) ). * + ,. < = > @ A[fj] U.S U.S.S.R * ** ***
TO: "to" as preposition or infinitive marker
    to
UH: interjection
    Goodbye Goody Gosh Wow Jeepers Jee-sus Hubba Hey Kee-reist Oops amen
    huh howdy uh dammit whammo shucks heck anyways whodunnit honey golly
    man baby diddle hush sonuvabitch ...
VB: verb, base form
    ask assemble assess assign assume atone attention avoid bake balkanize
    bank begin behold believe bend benefit bevel beware bless boil bomb
    boost brace break bring broil brush build ...
VBD: verb, past tense
    dipped pleaded swiped regummed soaked tidied convened halted registered
    cushioned exacted snubbed strode aimed adopted belied figgered
    speculated wore appreciated contemplated ...
VBG: verb, present participle or gerund
    telegraphing stirring focusing angering judging stalling lactating
    hankerin' alleging veering capping approaching traveling besieging
    encrypting interrupting erasing wincing ...
VBN: verb, past participle
    multihulled dilapidated aerosolized chaired languished panelized used
    experimented flourished imitated reunifed factored condensed sheared
    unsettled primed dubbed desired ...
VBP: verb, present tense, not 3rd person singular
    predominate wrap resort sue twist spill cure lengthen brush terminate
    appear tend stray glisten obtain comprise detest tease attract
    emphasize mold postpone sever return wag ...
VBZ: verb, present tense, 3rd person singular
    bases reconstructs marks mixes displeases seals carps weaves snatches
    slumps stretches authorizes smolders pictures emerges stockpiles
    seduces fizzes uses bolsters slaps speaks pleads ...
WDT: WH-determiner
    that what whatever which whichever
WP: WH-pronoun
    that what whatever whatsoever which who whom whosoever
WP$: WH-pronoun, possessive
    whose
WRB: Wh-adverb
    how however whence whenever where whereby whereever wherein whereof why
``: opening quotation mark
    ` ``

In [ ]:
sentence=word_tokenize("Third wave of corona virus is here")
nltk.pos_tag(sentence)

[('Third', 'JJ'),
 ('wave', 'NN'),
 ('of', 'IN'),
 ('corona', 'NN'),
 ('virus', 'NN'),
 ('is', 'VBZ'),
 ('here', 'RB')]

In [ ]:
#n gram in sentence analysis
import numpy as np
import pandas as pd
from sklearn import model_selection,naive_bayes,svm

In [ ]:
df=pd.read_csv("/content/sample_data/Reviews.csv",engine='python',error_bad_lines=False)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)
Skipping line 82850: unexpected end of data

In [ ]:
df.head()

   Id  ...                                               Text
0   1  ...  I have bought several of the Vitality canned d...
1   2  ...  Product arrived labeled as Jumbo Salted Peanut...
2   3  ...  This is a confection that has been around a fe...
3   4  ...  If you are looking for the secret ingredient i...
4   5  ...  Great taffy at a great price.  There was a wid...

[5 rows x 10 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82848 entries, 0 to 82847
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Id                      82848 non-null  int64
 1   ProductId               82848 non-null  object
 2   UserId                  82848 non-null  object
 3   ProfileName             82844 non-null  object
 4   HelpfulnessNumerator    82848 non-null  int64
 5   HelpfulnessDenominator  82848 non-null  int64
 6   Score                   82848 non-null  int64
 7   Time                    82848 non-null  int64
 8   Summary                 82846 non-null  object
 9   Text                    82848 non-null  object
dtypes: int64(5), object(5)
memory usage: 6.3+ MB

In [ ]:
df.describe()

                 Id  HelpfulnessNumerator  ...         Score          Time
count  82848.000000          82848.000000  ...  82848.000000  8.284800e+04
mean   41424.500000              1.604794  ...      4.149153  1.295363e+09
std    23916.301888              5.472931  ...      1.322098  4.776435e+07
min        1.000000              0.000000  ...      1.000000  9.486720e+08
25%    20712.750000              0.000000  ...      4.000000  1.269302e+09
50%    41424.500000              0.000000  ...      5.000000  1.310170e+09
75%    62136.250000              2.000000  ...      5.000000  1.331942e+09
max    82848.000000            398.000000  ...      5.000000  1.351210e+09

[8 rows x 5 columns]

In [ ]:
df.shape

(82848, 10)

In [ ]:
df.isnull().sum()

Id                        0
ProductId                 0
UserId                    0
ProfileName               4
HelpfulnessNumerator      0
HelpfulnessDenominator    0
Score                     0
Time                      0
Summary                   2
Text                      0
dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.isnull().sum()

Id                        0
ProductId                 0
UserId                    0
ProfileName               0
HelpfulnessNumerator      0
HelpfulnessDenominator    0
Score                     0
Time                      0
Summary                   0
Text                      0
dtype: int64

In [ ]:
df['Score'].value_counts()

5    51588
4    12170
1     7770
3     6714
2     4600
Name: Score, dtype: int64

In [ ]:
df['positively rated']=np.where(df['Score']>3,1,0)

In [ ]:
df.head()

   Id  ... positively rated
0   1  ...                1
1   2  ...                0
2   3  ...                1
3   4  ...                0
4   5  ...                1

[5 rows x 11 columns]

In [ ]:
df['positively rated'].value_counts()

1    63758
0    19084
Name: positively rated, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(df["Text"],df["positively rated"],random_state=8)

In [ ]:
print(x_train)

54010    About 4 years ago we were told that our dog Gr...
44267    My wife tried quite a few brands of K cup coff...
31355    This is a wonderful product. No sugar, no caff...
77484    This is a very good snack when you are watchin...
3282     Very good hot chocolate.  I have tried a few d...
                               ...
10376    I love Chuckles, so the temptation to buy some...
62431    I am not a big dark chocolate fan, but I decid...
18417    This salt is great! Not meant as a cooking sal...
25941    It's always disappointing when a great little ...
70089    Got my package today so I opened it up then pu...
Name: Text, Length: 62131, dtype: object

In [ ]:
print(y_train)

54010    1
44267    1
31355    1
77484    1
3282     1
        ..
10376    0
62431    0
18417    1
25941    1
70089    1
Name: positively rated, Length: 62131, dtype: int64

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
vect=CountVectorizer(min_df=5,ngram_range=(1,2),).fit(x_train)#min word count should 5 other discrd

In [ ]:
len(vect.get_feature_names())

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

125621

In [ ]:
v=vect.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

In [ ]:
v

['00',
 '00 am',
 '00 and',
 '00 at',
 '00 bag',
 '00 box',
 '00 br',
 '00 but',
 '00 can',
 '00 cheaper',
 '00 each',
 '00 for',
 '00 in',
 '00 is',
 '00 later',
 '00 less',
 '00 more',
 '00 off',
 '00 on',
 '00 per',
 '00 plus',
 '00 pound',
 '00 shipping',
 '00 so',
 '00 that',
 '00 the',
 '00 they',
 '00 this',
 '00 to',
 '00 worth',
 '00 you',
 '000',
 '000 calorie',
 '00pm',
 '01',
 '02',
 '03',
 '04',
 '05',
 '05 ounce',
 '06',
 '07',
 '08',
 '09',
 '09 br',
 '0g',
 '0g br',
 '0g fat',
 '0g protein',
 '0g sodium',
 '0g trans',
 '0mg',
 '0mg br',
 '0z',
 '10',
 '10 00',
 '10 000',
 '10 10',
 '10 11',
 '10 12',
 '10 14',
 '10 15',
 '10 20',
 '10 2011',
 '10 99',
 '10 am',
 '10 and',
 '10 at',
 '10 bag',
 '10 bags',
 '10 boxes',
 '10 br',
 '10 bucks',
 '10 calories',
 '10 cents',
 '10 cheaper',
 '10 count',
 '10 cup',
 '10 cups',
 '10 daily',
 '10 days',
 '10 different',
 '10 dollars',
 '10 each',
 '10 for',
 '10 grams',
 '10 hours',
 '10 if',
 '10 in',
 '10 it',
 '10 lb',
 '10 lbs',
 '10 less',
 '10 licks',
 '10 mg',
 '10 min',
 '10 mins',
 '10 minutes',
 '10 month',
 '10 months',
 '10 mos',
 '10 of',
 '10 off',
 '10 or',
 '10 ounce',
 '10 ounces',
 '10 oz',
 '10 pack',
 '10 packets',
 '10 packs',
 '10 per',
 '10 pieces',
 '10 pound',
 '10 pounds',
 '10 seconds',
 '10 servings',
 '10 so',
 '10 stars',
 '10 the',
 '10 they',
 '10 times',
 '10 to',
 '10 treats',
 '10 weeks',
 '10 which',
 '10 year',
 '10 years',
 '100',
 '100 and',
 '100 arabica',
 '100 as',
 '100 bags',
 '100 br',
 '100 cal',
 '100 calorie',
 '100 calories',
 '100 cals',
 '100 carbonated',
 '100 coconut',
 '100 count',
 '100 cups',
 '100 degree',
 '100 degrees',
 '100 for',
 '100 freeze',
 '100 fruit',
 '100 juice',
 '100 lb',
 '100 lbs',
 '100 maple',
 '100 more',
 '100 natural',
 '100 of',
 '100 organic',
 '100 pack',
 '100 percent',
 '100 pound',
 '100 pounds',
 '100 pure',
 '100 rda',
 '100 real',
 '100 recycled',
 '100 satisfaction',
 '100 satisfied',
 '100 tea',
 '100 times',
 '100 vitamin',
 '100 whole',
 '100 year',
 '100 years',
 '1000',
 '1000mg',
 '100g',
 '100mg',
 '103',
 '104',
 '105',
 '108',
 '10g',
 '10g br',
 '10g of',
 '10g protein',
 '10lb',
 '10lbs',
 '10mg',
 '10mg br',
 '10oz',
 '10oz cup',
 '10pm',
 '10th',
 '10th the',
 '10x',
 '11',
 '11 00',
 '11 10',
 '11 12',
 '11 2012',
 '11 30',
 '11 99',
 '11 and',
 '11 br',
 '11 for',
 '11 grams',
 '11 have',
 '11 in',
 '11 lbs',
 '11 month',
 '11 months',
 '11 of',
 '11 ounce',
 '11 ounces',
 '11 oz',
 '11 potato',
 '11 pound',
 '11 servings',
 '11 the',
 '11 to',
 '11 year',
 '11 years',
 '110',
 '110 calories',
 '1100',
 '1100 watt',
 '112',
 '114',
 '115',
 '11g',
 '11g of',
 '11oz',
 '11oz canister',
 '11th',
 '12',
 '12 00',
 '12 10',
 '12 12',
 '12 13',
 '12 14',
 '12 15',
 '12 16',
 '12 18',
 '12 2012',
 '12 24',
 '12 3oz',
 '12 50',
 '12 95',
 '12 99',
 '12 and',
 '12 as',
 '12 at',
 '12 bags',
 '12 bars',
 '12 big',
 '12 bottles',
 '12 box',
 '12 boxes',
 '12 br',
 '12 bucks',
 '12 but',
 '12 cans',
 '12 count',
 '12 cup',
 '12 cups',
 '12 different',
 '12 fl',
 '12 fluid',
 '12 for',
 '12 grams',
 '12 hours',
 '12 href',
 '12 in',
 '12 is',
 '12 it',
 '12 lb',
 '12 lbs',
 '12 minutes',
 '12 month',
 '12 months',
 '12 my',
 '12 of',
 '12 on',
 '12 or',
 '12 ounce',
 '12 ounces',
 '12 oz',
 '12 pack',
 '12 packages',
 '12 packets',
 '12 packs',
 '12 per',
 '12 pk',
 '12 pound',
 '12 pounds',
 '12 so',
 '12 that',
 '12 the',
 '12 this',
 '12 to',
 '12 was',
 '12 week',
 '12 weeks',
 '12 which',
 '12 year',
 '12 years',
 '12 yr',
 '120',
 '120 br',
 '120 calories',
 '1200',
 '125',
 '128',
 '12g',
 '12g br',
 '12g of',
 '12oz',
 '12oz can',
 '12oz cup',
 '12th',
 '13',
 '13 00',
 '13 and',
 '13 for',
 '13 grams',
 '13 month',
 '13 months',
 '13 of',
 '13 ounce',
 '13 oz',
 '13 year',
 '13 years',
 '13 yr',
 '130',
 '130 calories',
 '135',
 '135 calories',
 '13g',
 '13g of',
 '13th',
 '14',
 '14 00',
 '14 2012',
 '14 99',
 '14 and',
 '14 days',
 '14 grams',
 '14 month',
 '14 of',
 '14 or',
 '14 ounce',
 '14 ounces',
 '14 oz',
 '14 pounds',
 '14 that',
 '14 year',
 '14 years',
 '140',
 '140 calories',
 '144',
 '14g',
 '14oz',
 '15',
 '15 00',
 '15 20',
 '15 30',
 '15 5oz',
 '15 99',
 '15 and',
 '15 bags',
 '15 br',
 '15 calories',
 '15 cents',
 '15 discount',
 '15 dollars',
 '15 fifteen',
 '15 for',
 '15 grams',
 '15 lb',
 '15 lbs',
 '15 mg',
 '15 min',
 '15 mins',
 '15 minutes',
 '15 month',
 '15 months',
 '15 more',
 '15 of',
 '15 off',
 '15 on',
 '15 or',
 '15 ounce',
 '15 oz',
 '15 packs',
 '15 per',
 '15 pound',
 '15 pounds',
 '15 rda',
 '15 second',
 '15 seconds',
 '15 so',
 '15 times',
 '15 to',
 '15 year',
 '15 years',
 '15 yr',
 '150',
 '150 calories',
 '1500',
 '1519',
 '1519 mexican',
 '155',
 '155 mg',
 '155mg',
 '15g',
 '15g of',
 '15lb',
 '15lbs',
 '15mg',
 '15mg of',
 '15mg sodium',
 '15oz',
 '16',
 '16 00',
 '16 20',
 '16 9oz',
 '16 and',
 '16 br',
 '16 count',
 '16 fl',
 '16 for',
 '16 grams',
 '16 lb',
 '16 lbs',
 '16 month',
 '16 months',
 '16 of',
 '16 ounce',
 '16 ounces',
 '16 oz',
 '16 pack',
 '16 packages',
 '16 per',
 '16 pound',
 '16 servings',
 '16 to',
 '16 year',
 '16 years',
 '160',
 '160 calories',
 '1600',
 '160mg',
 '165',
 '16g',
 '16oz',
 '16oz of',
 '16th',
 '16th of',
 '17',
 '17 00',
 '17 99',
 '17 and',
 '17 br',
 '17 grams',
 '17 lbs',
 '17 month',
 '17 months',
 '17 ounce',
 '17 oz',
 '17 pound',
 '17 year',
 '17 years',
 '170',
 '170 calories',
 '170mg',
 '175',
 '17g',
 '17th',
 '18',
 '18 00',
 '18 12',
 '18 25',
 '18 95',
 '18 bags',
 '18 br',
 '18 count',
 '18 for',
 '18 grams',
 '18 hours',
 '18 lbs',
 '18 month',
 '18 months',
 '18 ounce',
 '18 oz',
 '18 pack',
 '18 per',
 '18 pound',
 '18 year',
 '18 years',
 '180',
 '180 calories',
 '180 degrees',
 '180 mg',
 '1800',
 '180mg',
 '185',
 '18g',
 '19',
 '19 br',
 '19 chips',
 '19 for',
 '19 month',
 '19 ounce',
 '19 year',
 '190',
 '190 calories',
 '192',
 '1930s',
 '1930s italy',
 '1950',
 '1960',
 '1970',
 '1970s',
 '1980',
 '1989',
 '1995',
 '1997',
 '1997 br',
 '1999',
 '19th',
 '1c',
 '1g',
 '1g br',
 '1g fiber',
 '1g of',
 '1g protein',
 '1g saturated',
 '1l',
 '1lb',
 '1lb bag',
 '1lb bags',
 '1lbs',
 '1oz',
 '1oz bags',
 '1oz serving',
 '1st',
 '1st and',
 '1st be',
 '1st blue',
 '1st cup',
 '1st order',
 '1st thing',
 '1st time',
 '1t',
 '1yr',
 '20',
 '20 00',
 '20 25',
 '20 30',
 '20 and',
 '20 at',
 '20 bag',
 '20 bags',
 '20 br',
 '20 bucks',
 '20 but',
 '20 calories',
 '20 count',
 '20 different',
 '20 dollars',
 '20 for',
 '20 grams',
 '20 if',
 '20 lb',
 '20 lbs',
 '20 mg',
 '20 min',
 '20 mins',
 '20 minutes',
 '20 month',
 '20 of',
 '20 off',
 '20 or',
 '20 ounce',
 '20 oz',
 '20 pack',
 '20 per',
 '20 pound',
 '20 pounds',
 '20 power',
 '20 seconds',
 '20 tea',
 '20 to',
 '20 vitamin',
 '20 words',
 '20 year',
 '20 years',
 '200',
 '200 calories',
 '200 mg',
 '2000',
 '2001',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2007 and',
 '2007 wasn',
 '2008',
 '2008 and',
 '2008 br',
 '2009',
 '2009 and',
 '2009 br',
 '200mg',
 '2010',
 '2010 and',
 '2010 br',
 '2010 so',
 '2010 the',
 '2011',
 '2011 and',
 '2011 br',
 '2011 the',
 '2011 they',
 '2011 when',
 '2012',
 '2012 and',
 '2012 br',
 '2012 my',
 '2012 so',
 '2012 the',
 '2012 update',
 '2013',
 '2013 br',
 '2013 so',
 '2014',
 '2015',
 '20ct',
 '20g',
 '20g br',
 '20g of',
 '20lb',
 '20lbs',
 '20mg',
 '20mg sodium',
 '20oz',
 '20oz bottle',
 '20th',
 '21',
 '21 for',
 '21 grams',
 '21 lbs',
 '21 month',
 '21 ounce',
 '21 oz',
 '210',
 '210 calories',
 '21g',
 '22',
 '22 2012',
 '22 grams',
 '22 month',
 '220',
 '220 calories',
 '220mg',
 '22g',
 '23',
 '23 00',
 '23 for',
 '23 grams',
 '23 watt',
 '230',
 '230 calories',
 '23g',
 '24',
 '24 00',
 '24 99',
 '24 and',
 '24 bag',
 '24 bags',
 '24 bottles',
 '24 br',
 '24 but',
 '24 can',
 '24 cans',
 '24 count',
 '24 cup',
 '24 cups',
 '24 for',
 '24 grams',
 '24 hour',
 '24 hours',
 '24 hrs',
 '24 in',
 '24 is',
 '24 it',
 '24 like',
 '24 of',
 '24 or',
 '24 ounce',
 '24 oz',
 '24 pack',
 '24 packs',
 '24 that',
 '24 the',
 '240',
 '240 calories',
 '240 count',
 '245',
 '24g',
 '24oz',
 '24pk',
 '24th',
 '25',
 '25 00',
 '25 30',
 '25 and',
 '25 br',
 '25 calories',
 '25 cents',
 '25 count',
 '25 crackers',
 '25 cups',
 '25 for',
 '25 grams',
 '25 lb',
 '25 lbs',
 '25 limit',
 '25 mg',
 '25 minutes',
 '25 more',
 '25 of',
 '25 off',
 '25 or',
 '25 ounce',
 '25 ounces',
 '25 oz',
 '25 per',
 '25 pound',
 '25 pounds',
 '25 to',
 '25 years',
 '250',
 '250 ml',
 '2500',
 '250ml',
 '250ml of',
 '25g',
 '25g of',
 '25lb',
 '25mg',
 '25mg br',
 '25oz',
 '25th',
 '26',
 '26 grams',
 '26 oz',
 '260',
 '260 calories',
 '26th',
 '27',
 '27 2012',
 '27 grams',
 '27 ounce',
 '27 oz',
 '270',
 '27g',
 '28',
 '28 grams',
 '28 lbs',
 '28 of',
 '28 ounce',
 '28 oz',
 '280',
 '280 calories',
 '28g',
 '28g of',
 '29',
 '29 at',
 '29 for',
 '29 grams',
 '290',
 '2c',
 '2g',
 '2g br',
 '2g each',
 '2g fiber',
 '2g of',
 '2g protein',
 '2g sugars',
 '2lb',
 '2lb bag',
 '2lbs',
 '2nd',
 '2nd and',
 '2nd bag',
 '2nd blue',
 '2nd box',
 '2nd cup',
 '2nd day',
 '2nd favorite',
 '2nd foods',
 '2nd ingredient',
 '2nd one',
 '2nd order',
 '2nd place',
 '2nd taste',
 '2nd time',
 '2oz',
 '2oz bag',
 '2oz bags',
 '2oz of',
 '2oz size',
 '2pm',
 '2t',
 '2t of',
 '2tbsp',
 '2x',
 '2x day',
 '2x the',
 '30',
 '30 00',
 '30 40',
 '30 45',
 '30 50',
 '30 am',
 '30 and',
 '30 box',
 '30 br',
 '30 but',
 '30 calories',
 '30 cents',
 '30 chews',
 '30 count',
 '30 days',
 '30 different',
 '30 dollars',
 '30 for',
 '30 grams',
 '30 is',
 '30 lb',
 '30 lbs',
 '30 less',
 '30 mg',
 '30 miles',
 '30 min',
 '30 mins',
 '30 minutes',
 '30 of',
 '30 or',
 '30 ounces',
 '30 per',
 '30 percent',
 '30 pound',
 '30 pounds',
 '30 sec',
 '30 seconds',
 '30 to',
 '30 years',
 '300',
 '300 biochemical',
 '300 calories',
 '300 for',
 '300 mg',
 '3000',
 '300mg',
 '300mgs',
 '300mgs day',
 '30am',
 '30g',
 '30lb',
 '30lbs',
 '30mg',
 '30pm',
 '30s',
 '30th',
 '31',
 '310',
 '32',
 '32 99',
 '32 ounce',
 '32 ounces',
 '32 oz',
 '320',
 '325',
 '32oz',
 '33',
 '33 grams',
 '33 ounce',
 '33 oz',
 '330',
 '330 calories',
 '33g',
 '33g of',
 '34',
 '34 grams',
 '34 ounce',
 '34 oz',
 '340',
 '34g',
 '34g of',
 '35',
 '35 br',
 '35 calories',
 '35 for',
 '35 grams',
 '35 lb',
 '35 lbs',
 '35 of',
 '35 oz',
 '35 per',
 '35 pound',
 '35 pounds',
 '35 years',
 '350',
 '350 degrees',
 '350 for',
 '350mgs',
 '350mgs for',
 '35g',
 '36',
 '36 bars',
 '36 count',
 '36 cups',
 '36 oz',
 '360',
 '360 calories',
 '365',
 '36g',
 '37',
 '375',
 '37g',
 '38',
 '39',
 '39 99',
 '3g',
 '3g br',
 '3g of',
 '3g protein',
 '3lbs',
 '3oz',
 '3oz bags',
 '3oz can',
 '3oz size',
 '3pm',
 '3rd',
 '3rd and',
 '3rd blue',
 '3rd box',
 '3rd of',
 '3rd time',
 '3rds',
 '3s',
 '3x',
 '3x the',
 '40',
 '40 00',
 '40 50',
 '40 and',
 '40 b40',
 '40 br',
 '40 calories',
 '40 cents',
 '40 count',
 '40 different',
 '40 for',
 '40 grams',
 '40 lb',
 '40 lbs',
 '40 minutes',
 '40 of',
 '40 or',
 '40 oz',
 '40 per',
 '40 percent',
 '40 pound',
 '40 pounds',
 '40 seconds',
 '40 to',
 '40 years',
 '400',
 '400 calories',
 '400 degrees',
 '40g',
 '40lb',
 '40lbs',
 '40mg',
 '41',
 '42',
 '425',
 '42g',
 '43',
 '44',
 '440',
 '45',
 '45 and',
 '45 calorie',
 '45 calories',
 '45 chews',
 '45 grams',
 '45 minutes',
 ...]

In [ ]:
x_train_vectorized=vect.transform(x_train)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(x_train_vectorized,y_train)

MultinomialNB()

In [ ]:
predictions=model.predict(vect.transform(x_test))

In [ ]:
print(predictions)

[1 1 1 ... 1 0 1]

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[ 3851   907]
 [ 1369 14584]]
              precision    recall  f1-score   support

           0       0.74      0.81      0.77      4758
           1       0.94      0.91      0.93     15953

    accuracy                           0.89     20711
   macro avg       0.84      0.86      0.85     20711
weighted avg       0.89      0.89      0.89     20711

In [ ]:
from sklearn.metrics import roc_auc_score    #roc 
print("AUC score is",roc_auc_score(y_test,predictions))

AUC score is 0.861779553046574